/**
 * Seed data for 20 realistic menu items.
 * Uses placeholder images from picsum.photos for consistent aspect ratios.
 */
const menuItems = [
  {
    name: 'Classic Vanilla Milkshake',
    description: 'Rich and creamy vanilla milkshake made with real ice cream and fresh milk. A timeless favourite.',
    price: 6.99,
    category: 'Milkshakes',
    tags: ['popular', 'classic'],
    image: 'https://picsum.photos/seed/milkshake1/400/300',
    isAvailable: true,
  },
  {
    name: 'Chocolate Fudge Milkshake',
    description: 'Indulgent chocolate milkshake blended with fudge sauce, chocolate ice cream, and whipped cream.',
    price: 7.99,
    category: 'Milkshakes',
    tags: ['popular', 'chocolate'],
    image: 'https://picsum.photos/seed/milkshake2/400/300',
    isAvailable: true,
  },
  {
    name: 'Strawberry Dream Milkshake',
    description: 'Fresh strawberry milkshake made with real strawberries, strawberry ice cream, and a hint of vanilla.',
    price: 7.49,
    category: 'Milkshakes',
    tags: ['seasonal', 'fruit'],
    image: 'https://picsum.photos/seed/milkshake3/400/300',
    isAvailable: true,
  },
  {
    name: 'Cookies & Cream Milkshake',
    description: 'Crushed chocolate cookie pieces blended into creamy vanilla ice cream, topped with cookie crumble.',
    price: 8.49,
    category: 'Milkshakes',
    tags: ['popular', 'cookies'],
    image: 'https://picsum.photos/seed/milkshake4/400/300',
    isAvailable: true,
  },
  {
    name: 'Salted Caramel Milkshake',
    description: 'Sweet and salty caramel milkshake with house-made caramel sauce and a pinch of sea salt.',
    price: 8.49,
    category: 'Milkshakes',
    tags: ['signature'],
    image: 'https://picsum.photos/seed/milkshake5/400/300',
    isAvailable: true,
  },
  {
    name: 'Brownie Explosion Sundae',
    description: 'Warm chocolate brownie topped with vanilla ice cream, hot fudge, whipped cream, and a cherry.',
    price: 9.99,
    category: 'Sundaes',
    tags: ['popular', 'chocolate', 'indulgent'],
    image: 'https://picsum.photos/seed/sundae1/400/300',
    isAvailable: true,
  },
  {
    name: 'Berrylicious Sundae',
    description: 'Mixed berry compote over vanilla ice cream with fresh berries, granola, and honey drizzle.',
    price: 8.99,
    category: 'Sundaes',
    tags: ['fruit', 'seasonal'],
    image: 'https://picsum.photos/seed/sundae2/400/300',
    isAvailable: true,
  },
  {
    name: 'Banana Split Sundae',
    description: 'Classic banana split with three scoops of ice cream, pineapple, strawberry, and chocolate toppings.',
    price: 10.49,
    category: 'Sundaes',
    tags: ['classic', 'popular'],
    image: 'https://picsum.photos/seed/sundae3/400/300',
    isAvailable: true,
  },
  {
    name: 'Caramel Pecan Sundae',
    description: 'Buttery pecan ice cream drizzled with warm caramel sauce, toasted pecans, and whipped cream.',
    price: 9.49,
    category: 'Sundaes',
    tags: ['signature', 'nutty'],
    image: 'https://picsum.photos/seed/sundae4/400/300',
    isAvailable: true,
  },
  {
    name: 'Mint Chocolate Chip Sundae',
    description: 'Refreshing mint ice cream with chocolate chips, hot fudge, and a dollop of whipped cream.',
    price: 8.99,
    category: 'Sundaes',
    tags: ['refreshing', 'chocolate'],
    image: 'https://picsum.photos/seed/sundae5/400/300',
    isAvailable: true,
  },
  {
    name: 'Vanilla Bean Ice Cream',
    description: 'Creamy vanilla bean ice cream made with real Madagascar vanilla. Simple and perfect.',
    price: 4.99,
    category: 'Ice Cream',
    tags: ['classic', 'popular'],
    image: 'https://picsum.photos/seed/icecream1/400/300',
    isAvailable: true,
  },
  {
    name: 'Belgian Chocolate Ice Cream',
    description: 'Deep, rich Belgian chocolate ice cream crafted with premium cocoa for the ultimate chocolate experience.',
    price: 5.49,
    category: 'Ice Cream',
    tags: ['chocolate', 'premium'],
    image: 'https://picsum.photos/seed/icecream2/400/300',
    isAvailable: true,
  },
  {
    name: 'Mango Sorbet',
    description: 'Dairy-free mango sorbet bursting with tropical fruit flavour. A refreshing dairy-free option.',
    price: 5.49,
    category: 'Ice Cream',
    tags: ['vegan', 'fruit', 'refreshing'],
    image: 'https://picsum.photos/seed/icecream3/400/300',
    isAvailable: true,
  },
  {
    name: 'Pistachio Gelato',
    description: 'Authentic Italian-style pistachio gelato with real pistachio pieces. Smooth and nutty.',
    price: 5.99,
    category: 'Ice Cream',
    tags: ['premium', 'nutty'],
    image: 'https://picsum.photos/seed/icecream4/400/300',
    isAvailable: true,
  },
  {
    name: 'Cookies & Cream Ice Cream',
    description: 'Creamy vanilla ice cream packed with generous chunks of chocolate sandwich cookies.',
    price: 4.99,
    category: 'Ice Cream',
    tags: ['popular', 'cookies'],
    image: 'https://picsum.photos/seed/icecream5/400/300',
    isAvailable: true,
  },
  {
    name: 'Classic Chocolate Chip Cookie Dough',
    description: 'Our signature chocolate chip cookie dough, ready to bake or enjoy raw (safe-to-eat).',
    price: 6.99,
    category: 'Cookie Dough',
    tags: ['popular', 'classic'],
    image: 'https://picsum.photos/seed/cookie1/400/300',
    isAvailable: true,
  },
  {
    name: 'Double Chocolate Cookie Dough',
    description: 'Rich chocolate cookie dough loaded with dark and milk chocolate chunks for double the indulgence.',
    price: 7.49,
    category: 'Cookie Dough',
    tags: ['chocolate', 'indulgent'],
    image: 'https://picsum.photos/seed/cookie2/400/300',
    isAvailable: true,
  },
  {
    name: 'Peanut Butter Bliss Cookie Dough',
    description: 'Creamy peanut butter cookie dough with peanut butter chips and milk chocolate chunks.',
    price: 7.49,
    category: 'Cookie Dough',
    tags: ['signature', 'nutty'],
    image: 'https://picsum.photos/seed/cookie3/400/300',
    isAvailable: true,
  },
  {
    name: 'Iced Caramel Latte',
    description: 'Smooth espresso over ice with creamy milk and house-made caramel syrup.',
    price: 5.49,
    category: 'Coffee',
    tags: ['popular', 'coffee'],
    image: 'https://picsum.photos/seed/coffee1/400/300',
    isAvailable: true,
  },
  {
    name: 'Mocha Frappé',
    description: 'Blended chocolate and coffee frappé topped with whipped cream and chocolate drizzle.',
    price: 6.49,
    category: 'Coffee',
    tags: ['popular', 'chocolate', 'coffee'],
    image: 'https://picsum.photos/seed/coffee2/400/300',
    isAvailable: true,
  },
];

module.exports = menuItems;

